services:
    m6.data_collector.redis:
        class: M6Web\Bundle\RedisBundle\DataCollector\RedisDataCollector
        tags:
            - { name: data_collector, template: 'M6WebRedisBundle:Collector:redis', id: 'redis' }
